### ISSUE TITLE
Purple Textures

### ISSUE THREAD

**Issue by WeixiongLin** [karazijal/clevrtex-generation#3]
Hi I am faced with lost materials issue when reproducing,

I run `./local_test.bash` and find that the image is purple after rendering, which indicates sth is wrong with materials. But it shows
```bash
Set Sphere_0 to poliigonmetalspottydiscoloration001 from data/materials/PoliigonMetalSpottyDiscoloration001.blend
```
so I think the materials have been rightly loaded. Any advice for me?

![LOCAL_debug_000000](https://user-images.githubusercontent.com/43513739/151476756-778d3481-bc89-4474-9c24-62a2522343cd.png)

**Comment by WeixiongLin** [comment]
I use the materials provided in `/data/materials` and sth gets wrong during rendering, but when I use materials downloaded from elsewhere it works well.
![image](https://user-images.githubusercontent.com/43513739/151501480-1cc5c24a-1976-47bd-9e6e-b5223666472e.png)

**Comment by karazijal** [comment]
Hi,

The materials look purple because textures are missing. This happens if they have not been downloaded or have been misplaced. Please refer to section [Debugging textures](https://github.com/karazijal/clevrtex-generation#debugging-textures) for running self-check, which should identify what is missing. There is also a command line [option](https://github.com/karazijal/clevrtex-generation/blob/1abd620bcb0356d7c0f17edf27458783b118d810/clevrtex-gen/generate.py#L643) for using built-in resolver to source texture images from alternative locations.

Closing as no code changes required.

**Comment by DarlingHang** [comment]
I think in the README it should be stressed that even using materials provided in `/data/materials`, the related file should be downloaded from poliigon and put in the correct place. Taking some time to figure out that
